apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: builds.registry.svc.cluster.local/solsson/kafka-cli
    context: ./
    custom:
      buildCommand: ./ystack-build.sh
      dependencies:
        dockerfile:
          path: ./Dockerfile
    # TODO nodemon and verify sync path
    #sync:
    #  manual:
    #  - src: src/**
    #    dest: /usr/src/app
deploy:
  kustomize:
    path: ./
