    version: '2.1'
    services:

      zoo-0:
        image: solsson/zookeeper-native@sha256:e8e43153588fc106d1e90bc62b69ebe9983d73862efb83a6e024a814681b9d8a
        entrypoint: &entrypoint_zoo
        # kubectl kustomize github.com/Yolean/kubernetes-kafka/nonroot?ref=6021333ad9784fceff5f90c0e63704b4705250e0
        # + native-agent
        - /opt/java/openjdk/bin/java
        - -Dzookeeper.root.logger=INFO,CONSOLE
        - -XX:+HeapDumpOnOutOfMemoryError
        - -XX:OnOutOfMemoryError=kill
        - -cp
        - ./lib/zookeeper-prometheus-metrics-3.6.1.jar:./lib/zookeeper-jute-3.6.1.jar:./lib/zookeeper-3.6.1.jar:./lib/snappy-java-1.1.7.jar:./lib/slf4j-log4j12-1.7.25.jar:./lib/slf4j-api-1.7.25.jar:./lib/simpleclient_servlet-0.6.0.jar:./lib/simpleclient_hotspot-0.6.0.jar:./lib/simpleclient_common-0.6.0.jar:./lib/simpleclient-0.6.0.jar:./lib/netty-transport-native-unix-common-4.1.48.Final.jar:./lib/netty-transport-native-epoll-4.1.48.Final.jar:./lib/netty-transport-4.1.48.Final.jar:./lib/netty-resolver-4.1.48.Final.jar:./lib/netty-handler-4.1.48.Final.jar:./lib/netty-common-4.1.48.Final.jar:./lib/netty-codec-4.1.48.Final.jar:./lib/netty-buffer-4.1.48.Final.jar:./lib/metrics-core-3.2.5.jar:./lib/log4j-1.2.17.jar:./lib/json-simple-1.1.1.jar:./lib/jline-2.11.jar:./lib/jetty-util-9.4.24.v20191120.jar:./lib/jetty-servlet-9.4.24.v20191120.jar:./lib/jetty-server-9.4.24.v20191120.jar:./lib/jetty-security-9.4.24.v20191120.jar:./lib/jetty-io-9.4.24.v20191120.jar:./lib/jetty-http-9.4.24.v20191120.jar:./lib/javax.servlet-api-3.1.0.jar:./lib/jackson-databind-2.10.3.jar:./lib/jackson-core-2.10.3.jar:./lib/jackson-annotations-2.10.3.jar:./lib/commons-lang-2.6.jar:./lib/commons-cli-1.2.jar:./lib/audience-annotations-0.5.0.jar
        - -Dlog4j.configuration=file:/etc/kafka/log4j.properties
        - -Dzookeeper.datadir.autocreate=true
        - -Dzookeeper.db.autocreate=false
        - -agentpath:/opt/graalvm/lib/libnative-image-agent.so=config-merge-dir=/home/nonroot/native-config
        - org.apache.zookeeper.server.quorum.QuorumPeerMain
        command:
        - /etc/kafka/zookeeper.properties.zoo-0
        volumes:
        - ./native-usecases.sh.configs:/etc/kafka
        - ./native-usecases.sh.configs/myid.zoo-0:/home/nonroot/myid

      zoo-1:
        image: solsson/zookeeper-native@sha256:e8e43153588fc106d1e90bc62b69ebe9983d73862efb83a6e024a814681b9d8a
        depends_on:
        - zoo-0
        entrypoint: *entrypoint_zoo
        command:
        - /etc/kafka/zookeeper.properties.zoo-1
        volumes:
        - ./configs/zookeeper-server-start:/home/nonroot/native-config
        - ./native-usecases.sh.configs:/etc/kafka
        - ./native-usecases.sh.configs/myid.zoo-1:/home/nonroot/myid

      zoo-2:
        image: solsson/zookeeper-native@sha256:e8e43153588fc106d1e90bc62b69ebe9983d73862efb83a6e024a814681b9d8a
        depends_on:
        - zoo-1
        entrypoint: *entrypoint_zoo
        command:
        - /etc/kafka/zookeeper.properties.zoo-2
        volumes:
        - ./native-usecases.sh.configs:/etc/kafka
        - ./native-usecases.sh.configs/myid.zoo-2:/home/nonroot/myid

      kafka-0:
        image: solsson/kafka:nativeagent-kafka-server-start
        depends_on:
        - zoo-2
        volumes:
        - ./configs/kafka-server-start:/home/nonroot/native-config
        command:
        - /etc/kafka/server.properties
        - --override
        -   zookeeper.connect=zoo-1:2181
        - --override
        -   advertised.listeners=PLAINTEXT://kafka-0:9092
        - --override
        -   auto.create.topics.enable=false

      kafka-1:
        image: solsson/kafka:nativeagent-kafka-server-start
        depends_on:
        - kafka-0
        command:
        - /etc/kafka/server.properties
        - --override
        -   broker.id=1
        - --override
        -   zookeeper.connect=zoo-2:2181
        - --override
        -   advertised.listeners=PLAINTEXT://kafka-1:9092
        - --override
        -   auto.create.topics.enable=false

      step1:
        image: solsson/kafka:nativeagent-kafka-topics
        volumes: [             ./configs/kafka-topics:/home/nonroot/native-config ]
        command:
        - --bootstrap-server=kafka-0:9092
        - --create
        - --topic=topic1
        - --config
        -   compression.type=uncompressed

      step2:
        image: solsson/kafka:nativeagent-kafka-topics
        volumes: [             ./configs/kafka-topics:/home/nonroot/native-config ]
        command:
        - --zookeeper=zoo-0:2181
        - --create
        - --topic=topic1
        - --partitions=1
        - --replication-factor=1
        - --config
        -   compression.type=uncompressed
        - --if-not-exists

      step3:
        image: solsson/kafka:nativeagent-kafka-topics
        volumes: [             ./configs/kafka-topics:/home/nonroot/native-config ]
        command:
        - --bootstrap-server=kafka-0:9092
        - --list

      step4:
        image: solsson/kafka:nativeagent-kafka-configs
        volumes: [             ./configs/kafka-configs:/home/nonroot/native-config ]
        command:
        - --zookeeper=zoo-0:2181
        - --entity-type=topics
        - --entity-name=topic1
        - --alter
        -   --add-config
        -     retention.ms=-1

      step5:
        image: solsson/kafka:nativeagent-kafka-configs
        volumes: [             ./configs/kafka-configs:/home/nonroot/native-config ]
        command:
        - --bootstrap-server=kafka-0:9092
        - --entity-type=brokers
        - --entity-name=0
        - --alter
        -   --add-config
        -     min.insync.replicas=1

      step6:
        image: solsson/kafka:nativeagent-kafka-consumer-groups
        volumes: [             ./configs/kafka-consumer-groups:/home/nonroot/native-config ]
        command:
        - --bootstrap-server=kafka-0:9092
        - --group=testgroup
        - --topic=topic1
        - --reset-offsets
        - --execute
        - --to-latest

      step7:
        image: solsson/kafka:nativeagent-kafka-consumer-groups
        volumes: [             ./configs/kafka-consumer-groups:/home/nonroot/native-config ]
        command:
        - --bootstrap-server=kafka-0:9092
        - --group=testgroup
        - --describe

      kafkacat:
        image: edenhill/kafkacat:1.5.0
        depends_on:
        - kafka-0
        environment:
        - b=kafka-0:9092
        - t=topic1
        entrypoint:
        - /bin/sh
        - -c
        command:
        - |
          while true; do sleep 1 && kafkacat -b $$b -L -t $$t | grep 'partition '; done
